# Generated by Django 3.1.1 on 2020-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201027_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Descripción',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
