# Generated by Django 3.1.1 on 2020-11-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201027_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='carruselImagene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
        ),
    ]
